language: ruby
cache: bundler
rvm:
    - 2.2.0

before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test' -U postgres
    - rake db:migrate

script: bundle exec rake --trace
